### ISSUE TITLE
Where to add background and content scripts?

### ISSUE THREAD

**Issue by rajenderK7** [timelessco/react-vite-chrome-extension#2]
I am not able to figure out where to place the background and content scripts. And how shall we include them in the manifest.json

**Comment by mcnaveen** [comment]
After the `yarn build` is complete. You can place the background and content script inside the `dist` folder

**Comment by rajenderK7** [comment]
Thank you @mcnaveen

**Comment by amitpatil321** [comment]
and if you want background.js file while in development, put it in public folder.
